name: build_$(Date:yyyyMMdd)$(Rev:r)

trigger:
- master

  

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    pool:
      name: BuildPool 
    workspace: 
      clean: all
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'acr'
        repository: 'myrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

# Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   #condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     pool:
#       name: stagingPool 
#     environment: staging
#     strategy:
#       runOnce:
#         deploy:
#           steps:
        