name: build_$(Date:yyyyMMdd)$(Rev:r)

trigger:
- main

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushContainer
    pool:
      name: BuildPool 
    workspace: 
      clean: all
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'acr'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'acr'
        repository: 'myrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  
  jobs:
  - deployment: production
    displayName: Deploy to aks
    pool:
      name: BuildPool     
    environment: aks
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aks'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'kubernates/manifests/ingress.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
          # - task: Kubernetes@1
          #   inputs:
          #     connectionType: 'Kubernetes Service Connection'
          #     kubernetesServiceEndpoint: 'aks'
          #     namespace: 'default'
          #     command: 'create'
          #     useConfigurationFile: true
          #     configuration: 'kubernates/manifests/service.yaml'
          #     secretType: 'dockerRegistry'
          #     containerRegistryType: 'Azure Container Registry'
          
          - script: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml

          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aks'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'kubernates/manifests/database.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'
 
          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'aks'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'kubernates/manifests/deployment.yaml'
              secretType: 'generic'
              secretArguments: '--from-literal=HOST=0.0.0.0 --from-literal=PORT=8080 --from-literal=COOKIE_ENCRYPT_PWD=$(COOKIE_ENCRYPT_PWD) --from-literal=HOST_URL=$(HOST_URL) --from-literal=OKTA_CLIENT_ID=$(OKTA_CLIENT_ID) --from-literal=OKTA_CLIENT_SECRET=$(OKTA_CLIENT_SECRET) --from-literal=OKTA_ORG_URL=$(OKTA_ORG_URL) --from-literal=PGHOST=$(PG_HOST) --from-literal=PGUSERNAME=$(PG_USER) --from-literal=PGDATABASE=$(PG_USER) --from-literal=PGPASSWORD=$(PG_PASS) --from-literal=PGPORT=$(5432)'

              
              


#Continuous Delivery Process for Production Environment
