apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.2.0
  nodeSets:
    - name: default
      count: 1

      config:
        node.store.allow_mmap: false

      node.remote_cluster_client: false

      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: standard
# 6E0s1Wf4IwQ69Oc24Dc84vEZ
# *${data.kubernetes.container.id}.log

