apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PGPASSWORD

        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PGHOST
---
kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
